// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/argoproj/argo-cd/v3/pkg/apiclient/application"
	mock "github.com/stretchr/testify/mock"
	"google.golang.org/grpc"
)

// NewApplicationClient creates a new instance of ApplicationClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewApplicationClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *ApplicationClient {
	mock := &ApplicationClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ApplicationClient is an autogenerated mock type for the ApplicationClient type
type ApplicationClient struct {
	mock.Mock
}

type ApplicationClient_Expecter struct {
	mock *mock.Mock
}

func (_m *ApplicationClient) EXPECT() *ApplicationClient_Expecter {
	return &ApplicationClient_Expecter{mock: &_m.Mock}
}

// GetChangeRevision provides a mock function for the type ApplicationClient
func (_mock *ApplicationClient) GetChangeRevision(ctx context.Context, in *application.ChangeRevisionRequest, opts ...grpc.CallOption) (*application.ChangeRevisionResponse, error) {
	// grpc.CallOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetChangeRevision")
	}

	var r0 *application.ChangeRevisionResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *application.ChangeRevisionRequest, ...grpc.CallOption) (*application.ChangeRevisionResponse, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *application.ChangeRevisionRequest, ...grpc.CallOption) *application.ChangeRevisionResponse); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*application.ChangeRevisionResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *application.ChangeRevisionRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ApplicationClient_GetChangeRevision_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChangeRevision'
type ApplicationClient_GetChangeRevision_Call struct {
	*mock.Call
}

// GetChangeRevision is a helper method to define mock.On call
//   - ctx context.Context
//   - in *application.ChangeRevisionRequest
//   - opts ...grpc.CallOption
func (_e *ApplicationClient_Expecter) GetChangeRevision(ctx interface{}, in interface{}, opts ...interface{}) *ApplicationClient_GetChangeRevision_Call {
	return &ApplicationClient_GetChangeRevision_Call{Call: _e.mock.On("GetChangeRevision",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *ApplicationClient_GetChangeRevision_Call) Run(run func(ctx context.Context, in *application.ChangeRevisionRequest, opts ...grpc.CallOption)) *ApplicationClient_GetChangeRevision_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *application.ChangeRevisionRequest
		if args[1] != nil {
			arg1 = args[1].(*application.ChangeRevisionRequest)
		}
		var arg2 []grpc.CallOption
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *ApplicationClient_GetChangeRevision_Call) Return(changeRevisionResponse *application.ChangeRevisionResponse, err error) *ApplicationClient_GetChangeRevision_Call {
	_c.Call.Return(changeRevisionResponse, err)
	return _c
}

func (_c *ApplicationClient_GetChangeRevision_Call) RunAndReturn(run func(ctx context.Context, in *application.ChangeRevisionRequest, opts ...grpc.CallOption) (*application.ChangeRevisionResponse, error)) *ApplicationClient_GetChangeRevision_Call {
	_c.Call.Return(run)
	return _c
}
